
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from '@chakra-ui/react';
import {Navbar} from "@/Components/Navbar";
import {Footer} from '../Components/Footer'
import ClientLayout from '../Components/ClientLayout';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <head>
         {/* <style>
          {`
            body::-webkit-scrollbar {
              display: none;
            }
            body {
              -ms-overflow-style: none; 
              scrollbar-width: none;
            }
          `}
        </style> */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ClientLayout>
            <Navbar />
            <main className="pt-20 pb-6">
              {children}
            </main>
            <Footer />
      </ClientLayout>
       
      </body>
    </html>
  );
}
